# Generated by Django 3.2.12 on 2023-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drenching',
            fields=[
                ('drenching_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=30)),
                ('field2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=250)),
                ('farm_location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Item1', 'Item1'), ('Item2', 'Item2'), ('Item3', 'Item3')], max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=30)),
                ('field2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Spraying',
            fields=[
                ('spraying_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=30)),
                ('field2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StockUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('use', 'Use')], max_length=4)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('labour', 'Labour'), ('farm executive', 'Farm Executive'), ('inventory manager', 'Inventory Manager')], default='labour', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
