# Generated by Django 4.1.7 on 2023-03-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("labour", "Labour"),
                    ("farmexecutive", "Farm Executive"),
                    ("inventorymanager", "Inventory Manager"),
                ],
                default="labour",
                max_length=20,
            ),
        ),
    ]
