# Generated by Django 4.1.7 on 2023-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="transaction_type",
            field=models.CharField(
                choices=[("add", "Add"), ("use", "Use")], default="add", max_length=4
            ),
        ),
    ]
