# Generated by Django 4.1.7 on 2023-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0003_inventory_transaction_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="field1",
            new_name="recipe_name",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="field2",
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_content",
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="category_name",
            field=models.CharField(max_length=20),
        ),
    ]
