# Generated by Django 4.1.7 on 2023-03-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0005_rename_field1_spraying_spray_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drenching",
            old_name="field1",
            new_name="drench_name",
        ),
        migrations.RemoveField(
            model_name="drenching",
            name="field2",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="drenching",
            name="drench_content",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_app.recipe",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventory",
            name="category_name",
            field=models.CharField(max_length=250),
        ),
    ]
