# Generated by Django 4.1.7 on 2023-03-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0006_rename_field1_drenching_drench_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drenching",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default=None,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spraying",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default=None,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockusage",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default=None,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
