# Generated by Django 4.1.7 on 2023-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0007_drenching_status_spraying_status_stockusage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drenching",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default="failure",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="spraying",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default="failure",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stockusage",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default="failure",
                max_length=10,
            ),
        ),
    ]
