# Generated by Django 4.1.7 on 2023-03-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0009_alter_drenching_status_alter_spraying_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockusage",
            name="status",
        ),
    ]
