# Generated by Django 4.1.7 on 2023-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0010_remove_stockusage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="number_of_compound",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
