# Generated by Django 4.1.7 on 2023-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0011_recipe_number_of_compound"),
    ]

    operations = [
        migrations.CreateModel(
            name="RocketChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("sender", models.CharField(max_length=255)),
                ("created_at", models.CharField(max_length=100)),
            ],
        ),
    ]
