# Generated by Django 4.1.7 on 2023-04-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0012_rocketchatconversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("receiver", models.TextField()),
                ("farm", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="inventory",
            name="farm",
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name="user",
            name="farm",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_app.farm",
            ),
        ),
    ]
