# Generated by Django 4.1.7 on 2023-04-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0013_emaillog_inventory_farm_user_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="drenching",
            name="farm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_app.farm",
            ),
        ),
        migrations.AddField(
            model_name="spraying",
            name="farm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_app.farm",
            ),
        ),
        migrations.AddField(
            model_name="stockusage",
            name="farm",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="farm",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_app.farm",
            ),
        ),
    ]
