# Generated by Django 4.1.7 on 2023-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0014_drenching_farm_spraying_farm_stockusage_farm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="farm",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
